with open(r'C:\Users\dferr\.kimi\plans\wasp-rocket-blue-beetle.md', 'a', encoding='utf-8') as f:
    f.write('---\n\n')
    f.write('## 4. Critical Pitfalls & Warnings\n\n')
    f.write('1. **main.js is ~1970 lines (over 1500 budget).** Any additions to main.js should be minimal. Prefer extracting UI refresh logic to helper functions or the respective module classes.\n\n')
    f.write('2. **Dual resource architecture.** ResourceSystem (used by SkillSystem) and ArchetypeSystem._resources (used for capstones) are separate. Adding a magic resource for skills is done in ResourceSystem. Adding it as an archetype resource requires ArchetypeSystem changes too. Be clear which one you are targeting.\n\n')
    f.write('3. **Gear panel UI is hardcoded in 3 places:** index.html (static markup), main.js (dynamic refresh loop), and CSS in index.html <style>. Keep them in sync.\n\n')
    f.write('4. **LocalStorage keys:** apex_exosuit, apex_character. Changing save formats without migration logic will wipe existing player saves. Add version fields to saved data.\n\n')
    f.write('5. **Set bonuses are manufacturer-based, not slot-based.** Adding slots does not break set bonuses, but it makes 4pc easier to achieve. Consider capping set bonuses or adding slot-specific restrictions.\n\n')
    f.write('6. **AffixSystem rollAffixes() takes a slot parameter** but currently does NOT filter by slot. If you want shoulder pads to only roll defense affixes, add slot-based filtering to pickUnique().\n\n')
    f.write('7. **LegendaryPowerSystem reads affixes from a hardcoded slot list in main.js.** If you add slots and want legendary powers from accessories to work, ensure the refresh loop includes them.\n\n')
    f.write('8. **Player.getRPGStats()** delegates to CharacterSheet.getStats(). Any new stats must flow through CharacterSheet._defaultGearBonuses() or they will be dropped during getStats().\n\n')
    f.write('---\n\n')
    f.write('## 5. Recommended Approach (Single Option)\n\n')
    f.write('Since the user wants to add ALL four features (armor slots, accessories, magic resource, new item types), the recommended approach is:\n\n')
    f.write('**Unified Gear & Inventory Expansion**\n\n')
    f.write('1. Treat accessories as first-class ExoSuit slots (same equip/unequip/bonus flow)\n')
    f.write('2. Add 2-3 new armor slots (shoulders, chestplate, belt) + 3 accessory slots (amulet, ring left, ring right)\n')
    f.write('3. Add MAGIC to ResourceSystem as a standalone resource type\n')
    f.write('4. Create a lightweight InventorySystem for stackable items (consumables, crafting mats)\n')
    f.write('5. Wire InventorySystem into LootSystem pickups and ShopSystem buy/sell\n\n')
    f.write('This keeps the architecture consistent with the existing one-module-per-subsystem rule and avoids fragmenting item logic across multiple systems.\n')
print('ok')
